#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SCRIPT="${SCRIPT_DIR}/nepa3d_pretrain_patch_nepa_tokens_qf.sh"
DEFAULT_WORKDIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
WORKDIR="${WORKDIR:-${DEFAULT_WORKDIR}}"

GROUP_LIST="${GROUP_LIST:-qgah50055}"
RT_QF="${RT_QF:-1}"
WALLTIME="${WALLTIME:-12:00:00}"

RUN_SET="${RUN_SET:-patchnepa_tokens_$(date +%Y%m%d_%H%M%S)}"
RUN_TAG="${RUN_TAG:-run_${RUN_SET}}"
SAVE_DIR="${SAVE_DIR:-runs/patchnepa_tokens/${RUN_SET}}"
LOG_ROOT="${LOG_ROOT:-logs/patch_nepa_pretrain_tokens/${RUN_SET}}"
PBS_LOG_DIR="${PBS_LOG_DIR:-${WORKDIR}/${LOG_ROOT}}"
mkdir -p "${PBS_LOG_DIR}"
PBS_LOG_PATH="${PBS_LOG_PATH:-${PBS_LOG_DIR}/${RUN_TAG}.pbs.log}"

JOB_NAME="${JOB_NAME:-pntok_pt}"
QSUB_DEPEND="${QSUB_DEPEND:-}"

if ! command -v qsub >/dev/null 2>&1; then
  echo "ERROR: qsub not found in PATH"
  exit 1
fi

cmd=(
  qsub
  -l "rt_QF=${RT_QF}"
  -l "walltime=${WALLTIME}"
  -W "group_list=${GROUP_LIST}"
  -N "${JOB_NAME}"
  -o "${PBS_LOG_PATH}"
  -v "WORKDIR=${WORKDIR},RUN_TAG=${RUN_TAG},SAVE_DIR=${SAVE_DIR},LOG_ROOT=${LOG_ROOT},MIX_CONFIG=${MIX_CONFIG:-nepa3d/configs/shapenet_unpaired_mix_v2_tokens.yaml},MAX_STEPS=${MAX_STEPS:-10000},SAVE_EVERY=${SAVE_EVERY:-1000},BATCH=${BATCH:-8},NUM_WORKERS=${NUM_WORKERS:-8},SEED=${SEED:-0},LR=${LR:-3e-4},LR_SCHEDULER=${LR_SCHEDULER:-cosine},WARMUP_STEPS=${WARMUP_STEPS:--1},WARMUP_RATIO=${WARMUP_RATIO:-0.025},MIN_LR=${MIN_LR:-1e-6},WEIGHT_DECAY=${WEIGHT_DECAY:-0.05},MAX_GRAD_NORM=${MAX_GRAD_NORM:-0.0},GRAD_ACCUM=${GRAD_ACCUM:-1},N_SURF=${N_SURF:-2048},N_QRY=${N_QRY:-1024},N_RAY=${N_RAY:-0},TOKEN_QA_LAYOUT=${TOKEN_QA_LAYOUT:-split},PM_PC_NORM=${PM_PC_NORM:-1},PM_SCALE_TRANSLATE=${PM_SCALE_TRANSLATE:-1},PM_SCALE_LOW=${PM_SCALE_LOW:-0.6666667},PM_SCALE_HIGH=${PM_SCALE_HIGH:-1.5},PM_TRANSLATE=${PM_TRANSLATE:-0.2},PM_TRANSFORM_ANSWERS=${PM_TRANSFORM_ANSWERS:-1},PATCH_EMBED=${PATCH_EMBED:-fps_knn},PATCH_LOCAL_ENCODER=${PATCH_LOCAL_ENCODER:-pointmae_conv},PATCH_FPS_RANDOM_START=${PATCH_FPS_RANDOM_START:-1},GROUP_SIZE=${GROUP_SIZE:-32},NUM_GROUPS=${NUM_GROUPS:-64},PATCH_ORDER_MODE=${PATCH_ORDER_MODE:-morton},D_MODEL=${D_MODEL:-384},N_LAYERS=${N_LAYERS:-12},N_HEADS=${N_HEADS:-6},MLP_RATIO=${MLP_RATIO:-4.0},DROP_PATH_RATE=${DROP_PATH_RATE:-0.0},QK_NORM=${QK_NORM:-1},QK_NORM_AFFINE=${QK_NORM_AFFINE:-0},QK_NORM_BIAS=${QK_NORM_BIAS:-0},LAYERSCALE_VALUE=${LAYERSCALE_VALUE:-1e-5},ROPE_THETA=${ROPE_THETA:-100.0},BACKBONE_MODE=${BACKBONE_MODE:-nepa2d},ANSWER_IN_DIM=${ANSWER_IN_DIM:-0},ANSWER_MLP_LAYERS=${ANSWER_MLP_LAYERS:-2},ANSWER_POOL=${ANSWER_POOL:-max},LOSS_TARGET_MODE=${LOSS_TARGET_MODE:-content_tokens},LOSS_MASK_MODE=${LOSS_MASK_MODE:-answer_and_point_context},SKIP_K=${SKIP_K:-1},Q_MASK_PROB=${Q_MASK_PROB:-0.0},Q_MASK_MODE=${Q_MASK_MODE:-mask_token},DUAL_MASK_NEAR=${DUAL_MASK_NEAR:-0.0},DUAL_MASK_FAR=${DUAL_MASK_FAR:-0.0},DUAL_MASK_WINDOW=${DUAL_MASK_WINDOW:-0},DUAL_MASK_TYPE_AWARE=${DUAL_MASK_TYPE_AWARE:-0},USE_WANDB=${USE_WANDB:-1},WANDB_PROJECT=${WANDB_PROJECT:-patchnepa-pretrain},WANDB_ENTITY=${WANDB_ENTITY:-},WANDB_RUN_NAME=${WANDB_RUN_NAME:-},WANDB_GROUP=${WANDB_GROUP:-},WANDB_TAGS=${WANDB_TAGS:-tokens,v2},WANDB_MODE=${WANDB_MODE:-online},WANDB_LOG_EVERY=${WANDB_LOG_EVERY:-1},DIAG_EVERY=${DIAG_EVERY:-1}"
)
if [[ -n "${QSUB_DEPEND}" ]]; then
  cmd+=( -W "depend=${QSUB_DEPEND}" )
fi
cmd+=( "${SCRIPT}" )

job_id="$("${cmd[@]}")"
echo "[submitted] ${job_id}"
echo "[run_set] ${RUN_SET}"
echo "[run_tag] ${RUN_TAG}"
echo "[save_dir] ${SAVE_DIR}"
echo "[log_root] ${LOG_ROOT}"
echo "[pbs_log] ${PBS_LOG_PATH}"
