#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# Stage-2 mainline policy: always launch via multinode wrapper (DDP).
SCRIPT="${SCRIPT_DIR}/nepa3d_pretrain_patch_nepa_multinode_pbsdsh.sh"
DEFAULT_WORKDIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
WORKDIR="${WORKDIR:-${DEFAULT_WORKDIR}}"

GROUP_LIST="${GROUP_LIST:-qgah50055}"
RT_QF="${RT_QF:-4}"
WALLTIME="${WALLTIME:-24:00:00}"

# Stage-2 mainline default (2026-03-01+): Ray-enabled Patch-NEPA.
RUN_SET="${RUN_SET:-patchnepa_rayqa_$(date +%Y%m%d_%H%M%S)}"
RUN_TAG="${RUN_TAG:-run_rayqa_${RUN_SET}}"
SAVE_DIR="${SAVE_DIR:-runs/patchnepa_rayqa/${RUN_SET}}"
LOG_ROOT="${LOG_ROOT:-logs/patch_nepa_pretrain/${RUN_SET}}"

N_POINT="${N_POINT:-1024}"
N_RAY="${N_RAY:-1024}"
USE_RAY_PATCH="${USE_RAY_PATCH:-1}"
INCLUDE_RAY_UNC="${INCLUDE_RAY_UNC:-0}"
RAY_ASSIGN_MODE="${RAY_ASSIGN_MODE:-proxy_sphere}"
RAY_USE_ORIGIN="${RAY_USE_ORIGIN:-0}"
RAY_PROXY_RADIUS_SCALE="${RAY_PROXY_RADIUS_SCALE:-1.05}"
RAY_NUM_GROUPS="${RAY_NUM_GROUPS:-32}"
RAY_GROUP_SIZE="${RAY_GROUP_SIZE:-32}"
RAY_POOL_MODE="${RAY_POOL_MODE:-amax}"
BATCH="${BATCH:-8}"
EPOCHS="${EPOCHS:-100}"
NUM_WORKERS="${NUM_WORKERS:-8}"
LR="${LR:-3e-4}"
SEED="${SEED:-0}"
USE_EMA="${USE_EMA:-0}"
EMA_DECAY="${EMA_DECAY:-0.9999}"
DIAG_COPY="${DIAG_COPY:-1}"
DIAG_EVERY="${DIAG_EVERY:-100}"
DIAG_K="${DIAG_K:-1}"
LOSS_TARGET_MODE="${LOSS_TARGET_MODE:-full_z}"   # full_z | content_tokens
Q_MASK_PROB="${Q_MASK_PROB:-0.0}"
Q_MASK_WARMUP_EPOCHS="${Q_MASK_WARMUP_EPOCHS:-0.0}"
Q_MASK_MODE="${Q_MASK_MODE:-mask_token}"   # mask_token | zero
USE_WANDB="${USE_WANDB:-1}"
WANDB_PROJECT="${WANDB_PROJECT:-patchnepa-pretrain}"
WANDB_ENTITY="${WANDB_ENTITY:-}"
WANDB_RUN_NAME="${WANDB_RUN_NAME:-${RUN_TAG}}"
WANDB_GROUP="${WANDB_GROUP:-patchnepa-pretrain}"
WANDB_TAGS="${WANDB_TAGS:-stage2,patchnepa,pretrain}"
WANDB_MODE="${WANDB_MODE:-online}"
WANDB_LOG_EVERY="${WANDB_LOG_EVERY:-50}"
WANDB_API_KEY="${WANDB_API_KEY:-}"
WANDB_BASE_URL="${WANDB_BASE_URL:-https://api.wandb.ai}"
LR_SCHEDULER="${LR_SCHEDULER:-cosine}"
WARMUP_RATIO="${WARMUP_RATIO:-0.025}"
WARMUP_EPOCHS="${WARMUP_EPOCHS:-}"
STAGE2_STRICT_LR_POLICY="${STAGE2_STRICT_LR_POLICY:-1}"
AUTO_RESUME="${AUTO_RESUME:-1}"
RESUME_OPTIMIZER="${RESUME_OPTIMIZER:-1}"
MAX_GRAD_NORM="${MAX_GRAD_NORM:-0.0}"
NPROC_PER_NODE="${NPROC_PER_NODE:-4}"
MASTER_PORT="${MASTER_PORT:-29410}"
DDP_LOG_ROOT="${DDP_LOG_ROOT:-${WORKDIR}/logs/ddp_patch_nepa_pretrain}"
NCCL_STABLE_MODE="${NCCL_STABLE_MODE:-0}"
ENABLE_ECC_PREFLIGHT="${ENABLE_ECC_PREFLIGHT:-1}"
NCCL_P2P_DISABLE="${NCCL_P2P_DISABLE:-}"
NCCL_NET_GDR_LEVEL="${NCCL_NET_GDR_LEVEL:-}"
TORCH_NCCL_ENABLE_MONITORING="${TORCH_NCCL_ENABLE_MONITORING:-}"
TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC="${TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC:-}"

PATCH_EMBED="${PATCH_EMBED:-fps_knn}"
GROUP_SIZE="${GROUP_SIZE:-32}"
NUM_GROUPS="${NUM_GROUPS:-64}"
SERIAL_ORDER="${SERIAL_ORDER:-morton}"
SERIAL_BITS="${SERIAL_BITS:-10}"
QK_NORM_AFFINE="${QK_NORM_AFFINE:-0}"
QK_NORM_BIAS="${QK_NORM_BIAS:-0}"
LAYERSCALE_VALUE="${LAYERSCALE_VALUE:-1e-5}"
ROPE_THETA="${ROPE_THETA:-100.0}"
D_MODEL="${D_MODEL:-384}"
N_LAYERS="${N_LAYERS:-12}"
N_HEADS="${N_HEADS:-6}"
MLP_RATIO="${MLP_RATIO:-4.0}"

AUG_ROTATE_Z="${AUG_ROTATE_Z:-0}"
AUG_SCALE_MIN="${AUG_SCALE_MIN:-1.0}"
AUG_SCALE_MAX="${AUG_SCALE_MAX:-1.0}"
AUG_TRANSLATE="${AUG_TRANSLATE:-0.0}"
AUG_JITTER_SIGMA="${AUG_JITTER_SIGMA:-0.0}"
AUG_JITTER_CLIP="${AUG_JITTER_CLIP:-0.0}"
AUG_RECOMPUTE_DIST="${AUG_RECOMPUTE_DIST:-0}"

MIX_CONFIG="${MIX_CONFIG:-nepa3d/configs/pretrain_mixed_shapenet_mesh_udf_onepass.yaml}"
PT_XYZ_KEY="${PT_XYZ_KEY:-pt_xyz_pool}"
PT_DIST_KEY="${PT_DIST_KEY:-pt_dist_pool}"
ABLATE_POINT_DIST="${ABLATE_POINT_DIST:-0}"
PT_SAMPLE_MODE="${PT_SAMPLE_MODE:-rfps_cached}"
PT_FPS_KEY="${PT_FPS_KEY:-auto}"
PT_RFPS_KEY="${PT_RFPS_KEY:-pt_rfps_order_bank}"
PT_RFPS_M="${PT_RFPS_M:-4096}"
POINT_ORDER_MODE="${POINT_ORDER_MODE:-morton}"
QA_TOKENS="${QA_TOKENS:-1}"
QA_LAYOUT="${QA_LAYOUT:-split_sep}"
QA_SEP_TOKEN="${QA_SEP_TOKEN:-1}"
QA_FUSE="${QA_FUSE:-add}"
ENCDEC_ARCH="${ENCDEC_ARCH:-0}"
USE_PT_DIST="${USE_PT_DIST:-1}"
USE_PT_GRAD="${USE_PT_GRAD:-0}"
ANSWER_MLP_LAYERS="${ANSWER_MLP_LAYERS:-2}"
ANSWER_POOL="${ANSWER_POOL:-max}"
NEPA_SKIP_K="${NEPA_SKIP_K:-1}"
NEPA_MULTI_K="${NEPA_MULTI_K:-}"
SKIPK_DISABLE_DUAL_MASK="${SKIPK_DISABLE_DUAL_MASK:-1}"
NEPA2D_POS="${NEPA2D_POS:-1}"
TYPE_SPECIFIC_POS="${TYPE_SPECIFIC_POS:-0}"
TYPE_POS_MAX_LEN="${TYPE_POS_MAX_LEN:-4096}"
MAX_LEN="${MAX_LEN:-4096}"
DUAL_MASK_NEAR="${DUAL_MASK_NEAR:-0.0}"
DUAL_MASK_FAR="${DUAL_MASK_FAR:-0.0}"
DUAL_MASK_WINDOW="${DUAL_MASK_WINDOW:-32}"
DUAL_MASK_TYPE_AWARE="${DUAL_MASK_TYPE_AWARE:-0}"
DUAL_MASK_WARMUP_FRAC="${DUAL_MASK_WARMUP_FRAC:-0.05}"

if ! command -v qsub >/dev/null 2>&1; then
  echo "ERROR: qsub not found in PATH"
  exit 1
fi

# Stage-2 strict execution rule:
# - pretrain must run on 16 GPUs (4 nodes x 4 GPUs).
if [[ "${RT_QF}" != "4" ]]; then
  echo "ERROR: Stage-2 pretrain requires RT_QF=4 (16 GPUs total). got RT_QF=${RT_QF}"
  exit 2
fi
if [[ "${NPROC_PER_NODE}" != "4" ]]; then
  echo "ERROR: Stage-2 pretrain requires NPROC_PER_NODE=4. got NPROC_PER_NODE=${NPROC_PER_NODE}"
  exit 2
fi
STAGE2_REQUIRE_GLOBAL_BATCH128="${STAGE2_REQUIRE_GLOBAL_BATCH128:-1}"
if [[ "${QA_SEP_TOKEN}" != "1" ]]; then
  echo "ERROR: Stage-2 policy requires QA_SEP_TOKEN=1 (got ${QA_SEP_TOKEN})"
  exit 2
fi
if [[ "${STAGE2_REQUIRE_GLOBAL_BATCH128}" == "1" ]]; then
  EFFECTIVE_GLOBAL_BATCH=$((BATCH * NPROC_PER_NODE * RT_QF))
  if [[ "${EFFECTIVE_GLOBAL_BATCH}" -ne 128 ]]; then
    echo "ERROR: Stage-2 pretrain requires effective_global_batch=128 (got ${EFFECTIVE_GLOBAL_BATCH})"
    echo "       (batch=${BATCH}, nproc_per_node=${NPROC_PER_NODE}, rt_qf=${RT_QF})"
    exit 2
  fi
fi


# Stage-2 strict optimizer policy:
# - keep Query/2D parity defaults unless explicitly disabled.
if [[ "${STAGE2_STRICT_LR_POLICY}" == "1" ]]; then
  LR_SCHEDULER="cosine"
  if [[ -z "${WARMUP_EPOCHS}" ]]; then
    WARMUP_RATIO="0.025"
  fi
fi

mkdir -p "${WORKDIR}/${LOG_ROOT}"
PBS_LOG_DIR="${PBS_LOG_DIR:-${WORKDIR}/${LOG_ROOT}}"
mkdir -p "${PBS_LOG_DIR}"
PBS_LOG_PATH="${PBS_LOG_PATH:-${PBS_LOG_DIR}/${RUN_TAG}.pbs.log}"

JOB_NAME="${JOB_NAME:-patchnepa_rayqa}"
QSUB_DEPEND="${QSUB_DEPEND:-}"
STAGE2_REQUIRE_RAY="${STAGE2_REQUIRE_RAY:-1}"

if [[ "${STAGE2_REQUIRE_RAY}" == "1" ]]; then
  if [[ "${USE_RAY_PATCH}" != "1" ]]; then
    echo "ERROR: Stage-2 mainline requires USE_RAY_PATCH=1 (got ${USE_RAY_PATCH})"
    exit 2
  fi
  if ! [[ "${N_RAY}" =~ ^[0-9]+$ ]] || [[ "${N_RAY}" -le 0 ]]; then
    echo "ERROR: Stage-2 mainline requires N_RAY>0 (got ${N_RAY})"
    exit 2
  fi
fi

cmd=(
  qsub
  -l "rt_QF=${RT_QF}"
  -l "walltime=${WALLTIME}"
  -W "group_list=${GROUP_LIST}"
  -N "${JOB_NAME}"
  -o "${PBS_LOG_PATH}"
  -v "WORKDIR=${WORKDIR},RUN_TAG=${RUN_TAG},SAVE_DIR=${SAVE_DIR},LOG_ROOT=${LOG_ROOT},MIX_CONFIG=${MIX_CONFIG},N_POINT=${N_POINT},N_RAY=${N_RAY},USE_RAY_PATCH=${USE_RAY_PATCH},STAGE2_REQUIRE_RAY=${STAGE2_REQUIRE_RAY},INCLUDE_RAY_UNC=${INCLUDE_RAY_UNC},RAY_ASSIGN_MODE=${RAY_ASSIGN_MODE},RAY_USE_ORIGIN=${RAY_USE_ORIGIN},RAY_PROXY_RADIUS_SCALE=${RAY_PROXY_RADIUS_SCALE},RAY_NUM_GROUPS=${RAY_NUM_GROUPS},RAY_GROUP_SIZE=${RAY_GROUP_SIZE},RAY_POOL_MODE=${RAY_POOL_MODE},BATCH=${BATCH},EPOCHS=${EPOCHS},NUM_WORKERS=${NUM_WORKERS},LR=${LR},SEED=${SEED},USE_EMA=${USE_EMA},EMA_DECAY=${EMA_DECAY},DIAG_COPY=${DIAG_COPY},DIAG_EVERY=${DIAG_EVERY},DIAG_K=${DIAG_K},LOSS_TARGET_MODE=${LOSS_TARGET_MODE},Q_MASK_PROB=${Q_MASK_PROB},Q_MASK_WARMUP_EPOCHS=${Q_MASK_WARMUP_EPOCHS},Q_MASK_MODE=${Q_MASK_MODE},USE_WANDB=${USE_WANDB},WANDB_PROJECT=${WANDB_PROJECT},WANDB_ENTITY=${WANDB_ENTITY},WANDB_RUN_NAME=${WANDB_RUN_NAME},WANDB_GROUP=${WANDB_GROUP},WANDB_TAGS=${WANDB_TAGS},WANDB_MODE=${WANDB_MODE},WANDB_LOG_EVERY=${WANDB_LOG_EVERY},WANDB_API_KEY=${WANDB_API_KEY},WANDB_BASE_URL=${WANDB_BASE_URL},LR_SCHEDULER=${LR_SCHEDULER},WARMUP_RATIO=${WARMUP_RATIO},WARMUP_EPOCHS=${WARMUP_EPOCHS},AUTO_RESUME=${AUTO_RESUME},RESUME_OPTIMIZER=${RESUME_OPTIMIZER},MAX_GRAD_NORM=${MAX_GRAD_NORM},PATCH_EMBED=${PATCH_EMBED},GROUP_SIZE=${GROUP_SIZE},NUM_GROUPS=${NUM_GROUPS},SERIAL_ORDER=${SERIAL_ORDER},SERIAL_BITS=${SERIAL_BITS},QK_NORM_AFFINE=${QK_NORM_AFFINE},QK_NORM_BIAS=${QK_NORM_BIAS},LAYERSCALE_VALUE=${LAYERSCALE_VALUE},ROPE_THETA=${ROPE_THETA},D_MODEL=${D_MODEL},N_LAYERS=${N_LAYERS},N_HEADS=${N_HEADS},MLP_RATIO=${MLP_RATIO},AUG_ROTATE_Z=${AUG_ROTATE_Z},AUG_SCALE_MIN=${AUG_SCALE_MIN},AUG_SCALE_MAX=${AUG_SCALE_MAX},AUG_TRANSLATE=${AUG_TRANSLATE},AUG_JITTER_SIGMA=${AUG_JITTER_SIGMA},AUG_JITTER_CLIP=${AUG_JITTER_CLIP},AUG_RECOMPUTE_DIST=${AUG_RECOMPUTE_DIST},PT_XYZ_KEY=${PT_XYZ_KEY},PT_DIST_KEY=${PT_DIST_KEY},ABLATE_POINT_DIST=${ABLATE_POINT_DIST},PT_SAMPLE_MODE=${PT_SAMPLE_MODE},PT_FPS_KEY=${PT_FPS_KEY},PT_RFPS_KEY=${PT_RFPS_KEY},PT_RFPS_M=${PT_RFPS_M},POINT_ORDER_MODE=${POINT_ORDER_MODE},QA_TOKENS=${QA_TOKENS},QA_LAYOUT=${QA_LAYOUT},QA_SEP_TOKEN=${QA_SEP_TOKEN},QA_FUSE=${QA_FUSE},ENCDEC_ARCH=${ENCDEC_ARCH},USE_PT_DIST=${USE_PT_DIST},USE_PT_GRAD=${USE_PT_GRAD},ANSWER_MLP_LAYERS=${ANSWER_MLP_LAYERS},ANSWER_POOL=${ANSWER_POOL},NEPA_SKIP_K=${NEPA_SKIP_K},NEPA_MULTI_K=${NEPA_MULTI_K},SKIPK_DISABLE_DUAL_MASK=${SKIPK_DISABLE_DUAL_MASK},NEPA2D_POS=${NEPA2D_POS},TYPE_SPECIFIC_POS=${TYPE_SPECIFIC_POS},TYPE_POS_MAX_LEN=${TYPE_POS_MAX_LEN},MAX_LEN=${MAX_LEN},DUAL_MASK_NEAR=${DUAL_MASK_NEAR},DUAL_MASK_FAR=${DUAL_MASK_FAR},DUAL_MASK_WINDOW=${DUAL_MASK_WINDOW},DUAL_MASK_TYPE_AWARE=${DUAL_MASK_TYPE_AWARE},DUAL_MASK_WARMUP_FRAC=${DUAL_MASK_WARMUP_FRAC},NPROC_PER_NODE=${NPROC_PER_NODE},MASTER_PORT=${MASTER_PORT},DDP_LOG_ROOT=${DDP_LOG_ROOT},NCCL_STABLE_MODE=${NCCL_STABLE_MODE},ENABLE_ECC_PREFLIGHT=${ENABLE_ECC_PREFLIGHT},NCCL_P2P_DISABLE=${NCCL_P2P_DISABLE},NCCL_NET_GDR_LEVEL=${NCCL_NET_GDR_LEVEL},TORCH_NCCL_ENABLE_MONITORING=${TORCH_NCCL_ENABLE_MONITORING},TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC=${TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC}"
)
if [[ -n "${QSUB_DEPEND}" ]]; then
  cmd+=( -W "depend=${QSUB_DEPEND}" )
fi
cmd+=( "${SCRIPT}" )

job_id="$("${cmd[@]}")"
echo "[submitted] ${job_id}"
echo "[run_set] ${RUN_SET}"
echo "[run_tag] ${RUN_TAG}"
echo "[save_dir] ${SAVE_DIR}"
echo "[log_root] ${LOG_ROOT}"
echo "[pbs_log] ${PBS_LOG_PATH}"
