#!/usr/bin/env bash
set -euo pipefail

# Run or print the pretrain-order x finetune-order mismatch jobs generated by
# 10_make_order_mismatch_configs.py. Defaults to DRY_RUN=1.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKDIR="${WORKDIR:-$(cd "${SCRIPT_DIR}/../.." && pwd)}"
MANIFEST="${MANIFEST:-}"
FINETUNE_WRAPPER="${FINETUNE_WRAPPER:-${WORKDIR}/pointnepa/scripts/local/pointgpt_finetune_local_ddp.sh}"
DRY_RUN="${DRY_RUN:-1}"
PRETRAIN_ORDERS="${PRETRAIN_ORDERS:-}"
FINETUNE_ORDERS="${FINETUNE_ORDERS:-}"
SPLITS="${SPLITS:-}"
ONLY_MISMATCH="${ONLY_MISMATCH:-0}"
USE_WANDB="${USE_WANDB:-0}"
NPROC_PER_NODE="${NPROC_PER_NODE:-2}"
CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1}"
NUM_WORKERS="${NUM_WORKERS:-8}"
MASTER_PORT_BASE="${MASTER_PORT_BASE:-29900}"
VAL_FREQ="${VAL_FREQ:-1}"
FT_RECON_WEIGHT="${FT_RECON_WEIGHT:-0}"
SAVE_LAST_EVERY_EPOCH="${SAVE_LAST_EVERY_EPOCH:-0}"
PYTHON_BIN="${PYTHON_BIN:-python3}"

if [[ -z "${MANIFEST}" ]]; then
  MANIFEST="$(ls -1dt "${WORKDIR}"/posetnepa_mask_order_preflight/generated/order_mismatch_*/order_mismatch_manifest.json 2>/dev/null | head -n 1 || true)"
fi
if [[ -z "${MANIFEST}" || ! -f "${MANIFEST}" ]]; then
  echo "[error] mismatch manifest not found. Set MANIFEST=/path/to/order_mismatch_manifest.json"
  exit 2
fi
if [[ "${DRY_RUN}" != "1" && ! -x "${FINETUNE_WRAPPER}" ]]; then
  echo "[error] finetune wrapper missing or not executable: ${FINETUNE_WRAPPER}"
  exit 2
fi

mapfile -t ROWS < <("${PYTHON_BIN}" - "${MANIFEST}" "${PRETRAIN_ORDERS}" "${FINETUNE_ORDERS}" "${SPLITS}" "${ONLY_MISMATCH}" <<'PY'
import json
import sys

manifest = json.load(open(sys.argv[1]))
pre_orders = {x.strip() for x in sys.argv[2].split(",") if x.strip()}
ft_orders = {x.strip() for x in sys.argv[3].split(",") if x.strip()}
splits = {x.strip() for x in sys.argv[4].split(",") if x.strip()}
only_mismatch = sys.argv[5] == "1"
for row in manifest["rows"]:
    if pre_orders and row["pretrain_order"] not in pre_orders:
        continue
    if ft_orders and row["finetune_order"] not in ft_orders:
        continue
    if splits and row["split"] not in splits:
        continue
    if only_mismatch and row["pretrain_order"] == row["finetune_order"]:
        continue
    print("\t".join([
        row["row_id"],
        row["split"],
        row["pretrain_order"],
        row["finetune_order"],
        row["finetune_config"],
        row["finetune_exp"],
        row["ckpt_path"],
        str(row.get("ckpt_exists", False)),
    ]))
PY
)

if [[ "${#ROWS[@]}" -eq 0 ]]; then
  echo "[error] no mismatch rows selected"
  exit 2
fi

idx=0
for row in "${ROWS[@]}"; do
  IFS=$'\t' read -r ROW_ID SPLIT PRE_ORDER FT_ORDER FT_CFG EXP_NAME CKPT_PATH CKPT_EXISTS <<< "${row}"
  if [[ "${DRY_RUN}" != "1" && ! -f "${CKPT_PATH}" ]]; then
    echo "[error] checkpoint missing for ${ROW_ID}: ${CKPT_PATH}"
    exit 2
  fi
  MASTER_PORT=$((MASTER_PORT_BASE + idx))
  echo "=== MISMATCH row=${ROW_ID} split=${SPLIT} pre_order=${PRE_ORDER} ft_order=${FT_ORDER} ==="
  cmd=(env
    WORKDIR="${WORKDIR}"
    CONFIG_PATH="${FT_CFG}"
    EXP_NAME="${EXP_NAME}"
    CKPT_PATH="${CKPT_PATH}"
    USE_WANDB="${USE_WANDB}"
    NPROC_PER_NODE="${NPROC_PER_NODE}"
    CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES}"
    NUM_WORKERS="${NUM_WORKERS}"
    MASTER_PORT="${MASTER_PORT}"
    VAL_FREQ="${VAL_FREQ}"
    FT_RECON_WEIGHT="${FT_RECON_WEIGHT}"
    SAVE_LAST_EVERY_EPOCH="${SAVE_LAST_EVERY_EPOCH}"
    WANDB_GROUP="posetnepa_order_mismatch"
    WANDB_TAGS="posetnepa,order_mismatch,pre_${PRE_ORDER},ft_${FT_ORDER},split_${SPLIT}"
    "${FINETUNE_WRAPPER}"
  )
  printf '[cmd] '; printf '%q ' "${cmd[@]}"; printf '\n'
  if [[ "${DRY_RUN}" != "1" ]]; then
    "${cmd[@]}"
  fi
  idx=$((idx + 1))
done
