#!/usr/bin/env bash
set -euo pipefail

# Run or print jobs generated by 13_make_scratch_early_configs.py.
# Defaults to DRY_RUN=1 and does not launch training unless explicitly changed.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKDIR="${WORKDIR:-$(cd "${SCRIPT_DIR}/../.." && pwd)}"
MANIFEST="${MANIFEST:-}"
PRETRAIN_WRAPPER="${PRETRAIN_WRAPPER:-${WORKDIR}/pointnepa/scripts/local/pointgpt_train_local_ddp.sh}"
FINETUNE_WRAPPER="${FINETUNE_WRAPPER:-${WORKDIR}/pointnepa/scripts/local/pointgpt_finetune_local_ddp.sh}"
SCRATCH_WRAPPER="${SCRATCH_WRAPPER:-${SCRIPT_DIR}/12_pointgpt_finetune_scan_scratch.sh}"
DRY_RUN="${DRY_RUN:-1}"
RUN_PRETRAIN="${RUN_PRETRAIN:-1}"
RUN_FINETUNE="${RUN_FINETUNE:-1}"
INIT_KINDS="${INIT_KINDS:-}"  # scratch,early_pretrain,stage1_last,stage1_frozen
ORDERS="${ORDERS:-}"
SPLITS="${SPLITS:-}"
USE_WANDB="${USE_WANDB:-0}"
NPROC_PER_NODE="${NPROC_PER_NODE:-2}"
CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1}"
NUM_WORKERS="${NUM_WORKERS:-8}"
MASTER_PORT_BASE="${MASTER_PORT_BASE:-30000}"
VAL_FREQ="${VAL_FREQ:-1}"
FT_RECON_WEIGHT="${FT_RECON_WEIGHT:-0}"
SAVE_LAST_EVERY_EPOCH="${SAVE_LAST_EVERY_EPOCH:-0}"
PYTHON_BIN="${PYTHON_BIN:-python3}"

if [[ -z "${MANIFEST}" ]]; then
  MANIFEST="$(ls -1dt "${WORKDIR}"/posetnepa_mask_order_preflight/generated/scratch_early_*/scratch_early_manifest.json 2>/dev/null | head -n 1 || true)"
fi
if [[ -z "${MANIFEST}" || ! -f "${MANIFEST}" ]]; then
  echo "[error] scratch/early manifest not found. Set MANIFEST=/path/to/scratch_early_manifest.json"
  exit 2
fi
if [[ "${DRY_RUN}" != "1" ]]; then
  [[ -x "${PRETRAIN_WRAPPER}" ]] || { echo "[error] missing pretrain wrapper: ${PRETRAIN_WRAPPER}"; exit 2; }
  [[ -x "${FINETUNE_WRAPPER}" ]] || { echo "[error] missing finetune wrapper: ${FINETUNE_WRAPPER}"; exit 2; }
  [[ -x "${SCRATCH_WRAPPER}" ]] || { echo "[error] missing scratch wrapper: ${SCRATCH_WRAPPER}"; exit 2; }
fi

if [[ "${RUN_PRETRAIN}" == "1" ]]; then
  mapfile -t PRETRAIN_ROWS < <("${PYTHON_BIN}" - "${MANIFEST}" "${ORDERS}" <<'PY'
import json
import sys

manifest = json.load(open(sys.argv[1]))
orders = {x.strip() for x in sys.argv[2].split(",") if x.strip()}
for job in manifest.get("pretrain_jobs", []):
    if orders and job["order"] not in orders:
        continue
    print("\t".join([
        job["job_id"],
        job["order"],
        str(job["mask_ratio"]),
        str(job["epoch"]),
        job["pretrain_config"],
        job["exp_name"],
        job["expected_ckpt"],
        str(job.get("ckpt_exists", False)),
    ]))
PY
)
  idx=0
  for row in "${PRETRAIN_ROWS[@]}"; do
    IFS=$'\t' read -r JOB_ID ORDER MASK EPOCH CONFIG_PATH EXP_NAME EXPECTED_CKPT CKPT_EXISTS <<< "${row}"
    MASTER_PORT=$((MASTER_PORT_BASE + idx))
    echo "=== EARLY PRETRAIN job=${JOB_ID} order=${ORDER} mask=${MASK} epoch=${EPOCH} ==="
    if [[ "${CKPT_EXISTS}" == "True" || "${CKPT_EXISTS}" == "true" ]]; then
      echo "[skip] expected checkpoint already exists: ${EXPECTED_CKPT}"
      idx=$((idx + 1))
      continue
    fi
    cmd=(env
      WORKDIR="${WORKDIR}"
      CONFIG_PATH="${CONFIG_PATH}"
      EXP_NAME="${EXP_NAME}"
      USE_WANDB="${USE_WANDB}"
      NPROC_PER_NODE="${NPROC_PER_NODE}"
      CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES}"
      NUM_WORKERS="${NUM_WORKERS}"
      MASTER_PORT="${MASTER_PORT}"
      WANDB_GROUP="posetnepa_scratch_early_pretrain"
      WANDB_TAGS="posetnepa,scratch_early,pretrain,order_${ORDER},mask_${MASK},epoch_${EPOCH}"
      "${PRETRAIN_WRAPPER}"
    )
    printf '[cmd] '; printf '%q ' "${cmd[@]}"; printf '\n'
    if [[ "${DRY_RUN}" != "1" ]]; then
      "${cmd[@]}"
    fi
    idx=$((idx + 1))
  done
fi

if [[ "${RUN_FINETUNE}" == "1" ]]; then
  mapfile -t FT_ROWS < <("${PYTHON_BIN}" - "${MANIFEST}" "${INIT_KINDS}" "${ORDERS}" "${SPLITS}" <<'PY'
import json
import sys

manifest = json.load(open(sys.argv[1]))
init_kinds = {x.strip() for x in sys.argv[2].split(",") if x.strip()}
orders = {x.strip() for x in sys.argv[3].split(",") if x.strip()}
splits = {x.strip() for x in sys.argv[4].split(",") if x.strip()}
for job in manifest.get("finetune_jobs", []):
    if init_kinds and job["init_kind"] not in init_kinds:
        continue
    if orders and job["order"] not in orders:
        continue
    if splits and job["split"] not in splits:
        continue
    print("\t".join([
        job["job_id"],
        job["init_kind"],
        job["order"],
        str(job["mask_ratio"]),
        job["split"],
        str(job["source_epoch"]),
        job["finetune_config"],
        job["exp_name"],
        job["ckpt_path"],
        str(job.get("ckpt_exists", False)),
        "1" if job.get("freeze_backbone", False) else "0",
    ]))
PY
)
  ft_idx=0
  for row in "${FT_ROWS[@]}"; do
    IFS=$'\t' read -r JOB_ID INIT_KIND ORDER MASK SPLIT SOURCE_EPOCH FT_CFG EXP_NAME CKPT_PATH CKPT_EXISTS FREEZE_BACKBONE <<< "${row}"
    MASTER_PORT=$((MASTER_PORT_BASE + 100 + ft_idx))
    echo "=== SCRATCH/EARLY FT job=${JOB_ID} init=${INIT_KIND} order=${ORDER} split=${SPLIT} source_epoch=${SOURCE_EPOCH} ==="
    if [[ "${INIT_KIND}" == "scratch" ]]; then
      cmd=(env
        WORKDIR="${WORKDIR}"
        CONFIG_PATH="${FT_CFG}"
        EXP_NAME="${EXP_NAME}"
        USE_WANDB="${USE_WANDB}"
        NPROC_PER_NODE="${NPROC_PER_NODE}"
        CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES}"
        NUM_WORKERS="${NUM_WORKERS}"
        MASTER_PORT="${MASTER_PORT}"
        VAL_FREQ="${VAL_FREQ}"
        FT_RECON_WEIGHT="${FT_RECON_WEIGHT}"
        SAVE_LAST_EVERY_EPOCH="${SAVE_LAST_EVERY_EPOCH}"
        DRY_RUN="${DRY_RUN}"
        WANDB_GROUP="posetnepa_scratch_early"
        WANDB_TAGS="posetnepa,scratch_early,scratch,order_${ORDER},split_${SPLIT}"
        "${SCRATCH_WRAPPER}"
      )
    else
      if [[ "${DRY_RUN}" != "1" && ! -f "${CKPT_PATH}" ]]; then
        echo "[error] checkpoint missing for ${JOB_ID}: ${CKPT_PATH}"
        exit 2
      fi
      cmd=(env
        WORKDIR="${WORKDIR}"
        CONFIG_PATH="${FT_CFG}"
        EXP_NAME="${EXP_NAME}"
        CKPT_PATH="${CKPT_PATH}"
        USE_WANDB="${USE_WANDB}"
        NPROC_PER_NODE="${NPROC_PER_NODE}"
        CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES}"
        NUM_WORKERS="${NUM_WORKERS}"
        MASTER_PORT="${MASTER_PORT}"
        VAL_FREQ="${VAL_FREQ}"
        FT_RECON_WEIGHT="${FT_RECON_WEIGHT}"
        SAVE_LAST_EVERY_EPOCH="${SAVE_LAST_EVERY_EPOCH}"
        FREEZE_BACKBONE="${FREEZE_BACKBONE}"
        WANDB_GROUP="posetnepa_scratch_early"
        WANDB_TAGS="posetnepa,scratch_early,${INIT_KIND},order_${ORDER},mask_${MASK},split_${SPLIT},source_epoch_${SOURCE_EPOCH},frozen_${FREEZE_BACKBONE}"
        "${FINETUNE_WRAPPER}"
      )
    fi
    printf '[cmd] '; printf '%q ' "${cmd[@]}"; printf '\n'
    if [[ "${DRY_RUN}" != "1" ]]; then
      "${cmd[@]}"
    fi
    ft_idx=$((ft_idx + 1))
  done
fi
